### ISSUE TITLE
[Reviewer 1] Explanaition of overlapping section of individuals

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2016-HPCA-HPMOON#1]
- An intuition of the meaning of the term "overlapping sections of individuals" should be made clear(er) since the very beginning. For instance, in both the abstract and introduction this term is used but not defined, nor informally introduced. So, basically the true content of the paper becomes clear only with Figure 2 at page 7.

**Comment by JJ** [comment]
You get all the issues? Hoarder!

**Comment by fergunet** [comment]
They are still unassigned, feel free to assign the ones you like the most (it would be great if you pick the ones that you know how to write good and fancy 'sciency' paragraphs ).
