### ISSUE TITLE
[ASOCO-R1-R3] Add new references

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2016-HPCA-HPMOON#17]
Specially from ASOCO and the ones published in 2017

**Comment by pacastillo** [comment]
I have included the following references:

@article{KAUR2018183,
title = "A novel multi-objective bacteria foraging optimization algorithm (MOBFOA) for multi-objective scheduling",
journal = "Applied Soft Computing",
volume = "66",
pages = "183 - 195",
year = "2018",
issn = "1568-4946",
doi = "https://doi.org/10.1016/j.asoc.2018.02.011",
url = "http://www.sciencedirect.com/science/article/pii/S1568494618300681",
author = "Mandeep Kaur and Sanjay Kadam",
keywords = "BFOA, Scheduling, Cloud computing, Multi-objective, Makespan"
}

@article{XU2018268,
title = "Hybrid multi-objective evolutionary algorithms based on decomposition for wireless sensor network coverage optimization",
journal = "Applied Soft Computing",
volume = "68",
pages = "268 - 282",
year = "2018",
issn = "1568-4946",
doi = "https://doi.org/10.1016/j.asoc.2018.03.053",
url = "http://www.sciencedirect.com/science/article/pii/S1568494618301868",
author = "Ying Xu and Ou Ding and Rong Qu and Keqin Li",
keywords = "Coverage optimization, MOEA/D, Multi-objective optimization, Wireless sensor networks"
}

@article{LUO2017235,
title = "An artificial bee colony algorithm for multi-objective optimisation",
journal = "Applied Soft Computing",
volume = "50",
pages = "235 - 251",
year = "2017",
issn = "1568-4946",
doi = "https://doi.org/10.1016/j.asoc.2016.11.014",
url = "http://www.sciencedirect.com/science/article/pii/S156849461630583X",
author = "Jianping Luo and Qiqi Liu and Yun Yang and Xia Li and Min-rong Chen and Wenming Cao",
keywords = "Evolutionary computing, Intelligent computing, Swarm intelligence, Multi-objective optimisation, Diversity, Artificial bee colony algorithm"
}

@article{LIU2017344,
title = "Many-objective evolutionary optimization based on reference points",
journal = "Applied Soft Computing",
volume = "50",
pages = "344 - 355",
year = "2017",
issn = "1568-4946",
doi = "https://doi.org/10.1016/j.asoc.2016.11.009",
url = "http://www.sciencedirect.com/science/article/pii/S1568494616305786",
author = "Yiping Liu and Dunwei Gong and Xiaoyan Sun and Yong Zhang",
keywords = "Evolutionary optimization, Multi-objective optimization, Many-objective optimization, Reference point, Distance"
}

**Comment by fergunet** [comment]
Thanks @pacastillo If you read the papers, could you update this document with the information? It will be easier to add them as references in the text when needed :)

https://docs.google.com/spreadsheets/d/1Lg68wKlw2gJkO38mdYRHvi6Z6EeVjmTTOhGb99qfJw8/edit?usp=sharing
