### ISSUE TITLE
[Reviewer 1] Improve the conclusions

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2016-HPCA-HPMOON#4]
- The conclusions section seems inappropriate for a journal paper, and needs to be deepened.

**Comment by fergunet** [comment]
For example, @JJ I know you would nail this issue.

**Comment by JJ** [comment]
I should have been quiet...

**Comment by JJ** [comment]
Is this still current?

**Comment by fergunet** [comment]
Yes, feel free to add new explanations.
